# Generated by Django 3.1.1 on 2020-11-02 13:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneToOneTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('one_to_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests_app.onetoonetestmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PrimitiveDataModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f16a1bf9-4850-4294-ba3c-4e423de18895'), editable=False, primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tests_app.testingmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ManyToOneTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tests_app.testingmodel')),
            ],
        ),
    ]
